# Generated by Django 5.2.17 on 2026-09-25 19:33

import django.core.validators
import django.db.models.deletion
import news.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#B84318', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$')], verbose_name='Farbe')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Rubrik',
                'verbose_name_plural': 'Rubriken',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120, verbose_name='Anzeigename')),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(blank=True, max_length=2000, verbose_name='Kurzbeschreibung')),
                ('is_public', models.BooleanField(default=False, verbose_name='Öffentlich freigegeben')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorendarstellung',
                'verbose_name_plural': 'Autorendarstellungen',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('excerpt', models.TextField(blank=True, max_length=600, verbose_name='Teaser')),
                ('body', models.TextField(blank=True, verbose_name='Artikeltext')),
                ('body_text', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht'), ('archived', 'Archiviert')], default='draft', max_length=12, verbose_name='Status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlichungsdatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured', models.BooleanField(default=False, verbose_name='Aufmacher')),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='Rubrik')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-published_at', '-pk'],
                'permissions': [('can_publish_article', 'Darf Artikel veröffentlichen und Aufmacher wählen')],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=news.models.media_path, verbose_name='Datei')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Alternativtext')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Bildunterschrift')),
                ('mime_type', models.CharField(choices=[('image/jpeg', 'image/jpeg'), ('image/png', 'image/png'), ('image/webp', 'image/webp')], max_length=30, verbose_name='Dateityp')),
                ('width', models.PositiveIntegerField(verbose_name='Breite')),
                ('height', models.PositiveIntegerField(verbose_name='Höhe')),
                ('size', models.PositiveIntegerField(verbose_name='Dateigröße')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
        ),
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Bildunterschrift')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_placements', to='news.article')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='news.media')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hero_articles', to='news.media'),
        ),
        migrations.AddField(
            model_name='article',
            name='images',
            field=models.ManyToManyField(related_name='articles', through='news.ArticleMedia', to='news.media'),
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('publication_name', models.CharField(default='KAKTUS', max_length=80, verbose_name='Zeitungsname')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Untertitel')),
                ('school_name', models.CharField(default='Aggertal-Gymnasium', max_length=160, verbose_name='Schule')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.media')),
            ],
            options={
                'verbose_name': 'Zeitungseinstellung',
                'verbose_name_plural': 'Zeitungseinstellungen',
            },
        ),
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='news.article')),
            ],
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0), ('size__gt', 0), ('size__lte', 10485760), ('width__gt', 0)), name='media_positive_bounded_size'),
        ),
        migrations.AddConstraint(
            model_name='articlemedia',
            constraint=models.UniqueConstraint(fields=('article', 'media'), name='unique_article_media'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='news_articl_status_dad29a_idx'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'published', 'archived'])), name='article_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='published_has_date'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('featured', False), ('status', 'published'), _connector='OR'), name='featured_is_published'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(condition=models.Q(('featured', True)), fields=('featured',), name='one_featured_article'),
        ),
        migrations.AddConstraint(
            model_name='sitesetting',
            constraint=models.CheckConstraint(condition=models.Q(('id', 1)), name='single_site_setting'),
        ),
    ]
