# Generated by Django 5.2.17 on 2026-09-25 19:35

import django.db.models.expressions
import django.db.models.lookups
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.expressions.CombinedExpression(models.F('width'), '*', models.F('height')), 25000000), name='media_max_pixels'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(('mime_type__in', ['image/jpeg', 'image/png', 'image/webp'])), name='media_image_types'),
        ),
    ]
