# Generated by Django 5.2.17 on 2026-09-26 06:35

from django.db import migrations, models


def mark_existing_submissions(apps, schema_editor):
    Submission = apps.get_model("submissions", "Submission")
    Media = apps.get_model("news", "Media")
    Media.objects.filter(pk__in=Submission.objects.exclude(image=None).values("image_id")).update(submission_origin=True)


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_media_media_max_pixels_media_media_image_types'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='submission_origin',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(mark_existing_submissions, migrations.RunPython.noop),
    ]
