# Generated by Django 5.2.17 on 2026-09-26 16:31

import django.core.validators
import news.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_media_submission_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hero_focus_x',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Bildfokus horizontal (%)'),
        ),
        migrations.AddField(
            model_name='article',
            name='hero_focus_y',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Bildfokus vertikal (%)'),
        ),
        migrations.AddField(
            model_name='media',
            name='large_file',
            field=models.FileField(blank=True, editable=False, upload_to=news.models.media_path),
        ),
        migrations.AddField(
            model_name='media',
            name='large_height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='media',
            name='large_size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='media',
            name='large_width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='media',
            name='small_file',
            field=models.FileField(blank=True, editable=False, upload_to=news.models.media_path),
        ),
        migrations.AddField(
            model_name='media',
            name='small_height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='media',
            name='small_size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='media',
            name='small_width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('hero_focus_x__lte', 100), ('hero_focus_y__lte', 100)), name='article_focus_bounds'),
        ),
    ]
