# Generated by Django 5.2.17 on 2026-09-25 19:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_token_hash', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='news.article')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at', 'article'], name='reactions_r_created_8d9df3_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'visitor_token_hash'), name='one_heart_per_browser_article')],
            },
        ),
    ]
