# Generated by Django 5.2.17 on 2026-09-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_media_media_max_pixels_media_media_image_types'),
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.CheckConstraint(condition=models.Q(('visitor_token_hash__regex', '^[0-9a-f]{64}$')), name='reaction_sha256_hash'),
        ),
    ]
