# Generated by Django 5.2.17 on 2026-09-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_reaction_reaction_sha256_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitWindow',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
