# Generated by Django 5.2.17 on 2026-09-25 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name (intern)')),
                ('class_level', models.CharField(max_length=40, verbose_name='Klasse/Jahrgang (intern)')),
                ('title', models.CharField(max_length=240, verbose_name='Titel')),
                ('body', models.TextField(max_length=50000, verbose_name='Klartext')),
                ('authorship_confirmed', models.BooleanField(default=False, verbose_name='Selbst geschrieben')),
                ('status', models.CharField(choices=[('new', 'Neu'), ('in_review', 'In Prüfung'), ('rejected', 'Abgelehnt'), ('converted', 'Übernommen')], default='new', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('editor_note', models.TextField(blank=True, verbose_name='Interne Notiz')),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.article')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.media')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einsendung',
                'verbose_name_plural': 'Einsendungen',
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['new', 'in_review', 'rejected', 'converted'])), name='submission_valid_status'), models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', False), ('status', 'converted')), models.Q(models.Q(('status', 'converted'), _negated=True), ('article__isnull', True)), _connector='OR'), name='converted_has_article')],
            },
        ),
    ]
